export const MAHARASHTRA_BOARDS = [
  "Maharashtra State Board",
  "Savitribai Phule Pune University",
  "University of Mumbai",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Shivaji University Kolhapur",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "Kavayitri Bahinabai Chaudhari North Maharashtra University",
  "Punyashlok Ahilyadevi Holkar Solapur University",
  "Gondwana University",
  "SNDT Women's University",
];

export const EDUCATION_LEVELS = [
  "Class 1",
  "Class 2",
  "Class 3",
  "Class 4",
  "Class 5",
  "Class 6",
  "Class 7",
  "Class 8",
  "Class 9",
  "Class 10",
  "Class 11",
  "Class 12",
  "Diploma",
  "Engineering (BE/BTech)",
  "BSc",
  "BCA",
  "BA",
  "BCom",
  "Other",
];
