/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerPath = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'educationRequirements' : IDL.Text,
  'industry' : IDL.Text,
});
export const MoodEntry = IDL.Record({
  'stressLevel' : IDL.Nat,
  'date' : IDL.Int,
  'notes' : IDL.Text,
  'moodLevel' : IDL.Nat,
});
export const WellnessResource = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'type' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AssessmentResult = IDL.Record({
  'recommendedCareer' : IDL.Text,
  'user' : IDL.Principal,
  'matchScore' : IDL.Nat,
  'timestamp' : Time,
});
export const StudyNotes = IDL.Record({
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'board' : IDL.Text,
  'chapter' : IDL.Text,
  'className' : IDL.Text,
  'educationLevel' : IDL.Text,
});
export const AcademicLevel = IDL.Variant({
  'highSchool' : IDL.Null,
  'undergraduate' : IDL.Null,
  'postgraduate' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'academicLevel' : AcademicLevel,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'goals' : IDL.Text,
});
export const UserStatistics = IDL.Record({
  'usersWithAssessments' : IDL.Nat,
  'usersWithMoodEntries' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'usersWithProfiles' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCareerPath' : IDL.Func([CareerPath], [], []),
  'addMoodEntry' : IDL.Func([MoodEntry], [], []),
  'addWellnessResource' : IDL.Func([WellnessResource], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudyNotes' : IDL.Func([Time], [], []),
  'generateStudyNotes' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Time],
      [],
    ),
  'getAllAssessments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, AssessmentResult))],
      ['query'],
    ),
  'getAllCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getAllMoodEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, MoodEntry))],
      ['query'],
    ),
  'getAllStudyNotes' : IDL.Func([], [IDL.Vec(StudyNotes)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllWellnessResources' : IDL.Func(
      [],
      [IDL.Vec(WellnessResource)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerPathByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CareerPath)],
      ['query'],
    ),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getUserAssessments' : IDL.Func([], [IDL.Vec(AssessmentResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatistics' : IDL.Func([], [UserStatistics], ['query']),
  'getViewedResources' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCareerPath' : IDL.Func([IDL.Text], [], []),
  'removeWellnessResource' : IDL.Func([IDL.Text], [], []),
  'saveAssessmentResult' : IDL.Func([AssessmentResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveViewedResource' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerPath = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'educationRequirements' : IDL.Text,
    'industry' : IDL.Text,
  });
  const MoodEntry = IDL.Record({
    'stressLevel' : IDL.Nat,
    'date' : IDL.Int,
    'notes' : IDL.Text,
    'moodLevel' : IDL.Nat,
  });
  const WellnessResource = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'type' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AssessmentResult = IDL.Record({
    'recommendedCareer' : IDL.Text,
    'user' : IDL.Principal,
    'matchScore' : IDL.Nat,
    'timestamp' : Time,
  });
  const StudyNotes = IDL.Record({
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'board' : IDL.Text,
    'chapter' : IDL.Text,
    'className' : IDL.Text,
    'educationLevel' : IDL.Text,
  });
  const AcademicLevel = IDL.Variant({
    'highSchool' : IDL.Null,
    'undergraduate' : IDL.Null,
    'postgraduate' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'academicLevel' : AcademicLevel,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'goals' : IDL.Text,
  });
  const UserStatistics = IDL.Record({
    'usersWithAssessments' : IDL.Nat,
    'usersWithMoodEntries' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'usersWithProfiles' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCareerPath' : IDL.Func([CareerPath], [], []),
    'addMoodEntry' : IDL.Func([MoodEntry], [], []),
    'addWellnessResource' : IDL.Func([WellnessResource], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudyNotes' : IDL.Func([Time], [], []),
    'generateStudyNotes' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Time],
        [],
      ),
    'getAllAssessments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, AssessmentResult))],
        ['query'],
      ),
    'getAllCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getAllMoodEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, MoodEntry))],
        ['query'],
      ),
    'getAllStudyNotes' : IDL.Func([], [IDL.Vec(StudyNotes)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllWellnessResources' : IDL.Func(
        [],
        [IDL.Vec(WellnessResource)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerPathByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CareerPath)],
        ['query'],
      ),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getUserAssessments' : IDL.Func([], [IDL.Vec(AssessmentResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatistics' : IDL.Func([], [UserStatistics], ['query']),
    'getViewedResources' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCareerPath' : IDL.Func([IDL.Text], [], []),
    'removeWellnessResource' : IDL.Func([IDL.Text], [], []),
    'saveAssessmentResult' : IDL.Func([AssessmentResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveViewedResource' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };