/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AcademicLevel = { 'highSchool' : null } |
  { 'undergraduate' : null } |
  { 'postgraduate' : null };
export interface AssessmentResult {
  'recommendedCareer' : string,
  'user' : Principal,
  'matchScore' : bigint,
  'timestamp' : Time,
}
export interface CareerPath {
  'title' : string,
  'description' : string,
  'requiredSkills' : Array<string>,
  'educationRequirements' : string,
  'industry' : string,
}
export interface MoodEntry {
  'stressLevel' : bigint,
  'date' : bigint,
  'notes' : string,
  'moodLevel' : bigint,
}
export interface StudyNotes {
  'content' : string,
  'subject' : string,
  'user' : Principal,
  'timestamp' : Time,
  'board' : string,
  'chapter' : string,
  'className' : string,
  'educationLevel' : string,
}
export type Time = bigint;
export interface UserProfile {
  'academicLevel' : AcademicLevel,
  'interests' : Array<string>,
  'name' : string,
  'goals' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStatistics {
  'usersWithAssessments' : bigint,
  'usersWithMoodEntries' : bigint,
  'totalUsers' : bigint,
  'usersWithProfiles' : bigint,
}
export interface WellnessResource {
  'title' : string,
  'content' : string,
  'type' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCareerPath' : ActorMethod<[CareerPath], undefined>,
  'addMoodEntry' : ActorMethod<[MoodEntry], undefined>,
  'addWellnessResource' : ActorMethod<[WellnessResource], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudyNotes' : ActorMethod<[Time], undefined>,
  'generateStudyNotes' : ActorMethod<
    [string, string, string, string, string, string],
    Time
  >,
  'getAllAssessments' : ActorMethod<[], Array<[Principal, AssessmentResult]>>,
  'getAllCareerPaths' : ActorMethod<[], Array<CareerPath>>,
  'getAllMoodEntries' : ActorMethod<[], Array<[Principal, MoodEntry]>>,
  'getAllStudyNotes' : ActorMethod<[], Array<StudyNotes>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllWellnessResources' : ActorMethod<[], Array<WellnessResource>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerPathByTitle' : ActorMethod<[string], [] | [CareerPath]>,
  'getMoodHistory' : ActorMethod<[], Array<MoodEntry>>,
  'getUserAssessments' : ActorMethod<[], Array<AssessmentResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatistics' : ActorMethod<[], UserStatistics>,
  'getViewedResources' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCareerPath' : ActorMethod<[string], undefined>,
  'removeWellnessResource' : ActorMethod<[string], undefined>,
  'saveAssessmentResult' : ActorMethod<[AssessmentResult], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveViewedResource' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];