/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserStatistics {
    usersWithAssessments: bigint;
    usersWithMoodEntries: bigint;
    totalUsers: bigint;
    usersWithProfiles: bigint;
}
export type Time = bigint;
export interface StudyNotes {
    content: string;
    subject: string;
    user: Principal;
    timestamp: Time;
    board: string;
    chapter: string;
    className: string;
    educationLevel: string;
}
export interface AssessmentResult {
    recommendedCareer: string;
    user: Principal;
    matchScore: bigint;
    timestamp: Time;
}
export interface CareerPath {
    title: string;
    description: string;
    requiredSkills: Array<string>;
    educationRequirements: string;
    industry: string;
}
export interface WellnessResource {
    title: string;
    content: string;
    type: string;
}
export interface UserProfile {
    academicLevel: AcademicLevel;
    interests: Array<string>;
    name: string;
    goals: string;
}
export interface MoodEntry {
    stressLevel: bigint;
    date: bigint;
    notes: string;
    moodLevel: bigint;
}
export enum AcademicLevel {
    highSchool = "highSchool",
    undergraduate = "undergraduate",
    postgraduate = "postgraduate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCareerPath(path: CareerPath): Promise<void>;
    addMoodEntry(entry: MoodEntry): Promise<void>;
    addWellnessResource(resource: WellnessResource): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteStudyNotes(timestamp: Time): Promise<void>;
    generateStudyNotes(educationLevel: string, board: string, className: string, subject: string, chapter: string, content: string): Promise<Time>;
    getAllAssessments(): Promise<Array<[Principal, AssessmentResult]>>;
    getAllCareerPaths(): Promise<Array<CareerPath>>;
    getAllMoodEntries(): Promise<Array<[Principal, MoodEntry]>>;
    getAllStudyNotes(): Promise<Array<StudyNotes>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAllWellnessResources(): Promise<Array<WellnessResource>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCareerPathByTitle(title: string): Promise<CareerPath | null>;
    getMoodHistory(): Promise<Array<MoodEntry>>;
    getUserAssessments(): Promise<Array<AssessmentResult>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatistics(): Promise<UserStatistics>;
    getViewedResources(): Promise<Array<bigint>>;
    isCallerAdmin(): Promise<boolean>;
    removeCareerPath(title: string): Promise<void>;
    removeWellnessResource(title: string): Promise<void>;
    saveAssessmentResult(result: AssessmentResult): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveViewedResource(resourceId: bigint): Promise<void>;
}
import type { AcademicLevel as _AcademicLevel, CareerPath as _CareerPath, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCareerPath(arg0: CareerPath): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCareerPath(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCareerPath(arg0);
            return result;
        }
    }
    async addMoodEntry(arg0: MoodEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoodEntry(arg0);
            return result;
        }
    }
    async addWellnessResource(arg0: WellnessResource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWellnessResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWellnessResource(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteStudyNotes(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudyNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudyNotes(arg0);
            return result;
        }
    }
    async generateStudyNotes(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.generateStudyNotes(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateStudyNotes(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAllAssessments(): Promise<Array<[Principal, AssessmentResult]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessments();
            return result;
        }
    }
    async getAllCareerPaths(): Promise<Array<CareerPath>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCareerPaths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCareerPaths();
            return result;
        }
    }
    async getAllMoodEntries(): Promise<Array<[Principal, MoodEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMoodEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMoodEntries();
            return result;
        }
    }
    async getAllStudyNotes(): Promise<Array<StudyNotes>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyNotes();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWellnessResources(): Promise<Array<WellnessResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWellnessResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWellnessResources();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareerPathByTitle(arg0: string): Promise<CareerPath | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerPathByTitle(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerPathByTitle(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodHistory(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodHistory();
            return result;
        }
    }
    async getUserAssessments(): Promise<Array<AssessmentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAssessments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAssessments();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatistics(): Promise<UserStatistics> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatistics();
            return result;
        }
    }
    async getViewedResources(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewedResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewedResources();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeCareerPath(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCareerPath(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCareerPath(arg0);
            return result;
        }
    }
    async removeWellnessResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWellnessResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWellnessResource(arg0);
            return result;
        }
    }
    async saveAssessmentResult(arg0: AssessmentResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAssessmentResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAssessmentResult(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveViewedResource(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveViewedResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveViewedResource(arg0);
            return result;
        }
    }
}
function from_candid_AcademicLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicLevel): AcademicLevel {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerPath]): CareerPath | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicLevel: _AcademicLevel;
    interests: Array<string>;
    name: string;
    goals: string;
}): {
    academicLevel: AcademicLevel;
    interests: Array<string>;
    name: string;
    goals: string;
} {
    return {
        academicLevel: from_candid_AcademicLevel_n7(_uploadFile, _downloadFile, value.academicLevel),
        interests: value.interests,
        name: value.name,
        goals: value.goals
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highSchool: null;
} | {
    undergraduate: null;
} | {
    postgraduate: null;
}): AcademicLevel {
    return "highSchool" in value ? AcademicLevel.highSchool : "undergraduate" in value ? AcademicLevel.undergraduate : "postgraduate" in value ? AcademicLevel.postgraduate : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AcademicLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicLevel): _AcademicLevel {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicLevel: AcademicLevel;
    interests: Array<string>;
    name: string;
    goals: string;
}): {
    academicLevel: _AcademicLevel;
    interests: Array<string>;
    name: string;
    goals: string;
} {
    return {
        academicLevel: to_candid_AcademicLevel_n15(_uploadFile, _downloadFile, value.academicLevel),
        interests: value.interests,
        name: value.name,
        goals: value.goals
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicLevel): {
    highSchool: null;
} | {
    undergraduate: null;
} | {
    postgraduate: null;
} {
    return value == AcademicLevel.highSchool ? {
        highSchool: null
    } : value == AcademicLevel.undergraduate ? {
        undergraduate: null
    } : value == AcademicLevel.postgraduate ? {
        postgraduate: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
